### ISSUE TITLE
step to play rosbag

### ISSUE THREAD

**Issue by YuehChuan** [mcubelab/push-est-public#1]
**Thanks** for make this project available!
The paper and video is  written well, already explain 90% for the work.
If I am ICRA reviewer, I would like to vote for it.

Now  already launch pman and see the panel, rviz 
![push](https://user-images.githubusercontent.com/7314531/33657239-a21f503a-dab3-11e7-947d-2d5cef0d0f34.png)
![p1-rviz](https://user-images.githubusercontent.com/7314531/33657242-a3912e84-dab3-11e7-9ad4-72560c4b2364.png)

also put bag file under directory   $DATA_BASE/inputdata/multi_pushes_twofinger_gripper

if further instructions for playing around this work  would be grateful!
But if there are some consideration, because this is under review, it's ok.
I would try to figure out.

Thank you!

**Comment by peterkty** [comment]
That's great. 

I'm not sure if you have compiled things (catkin_make) and run ```push-est-public/software/config/environment.sh``` to set some environment variable. You should be able to see a robot in the rviz.

After that, rerun the pman and try the  ```run_playback_and_test_rect1``` script.

I'm happy to share the steps, but I have limited time right now. We can schedule a meeting to make it work. 

Thank you.

**Comment by YuehChuan** [comment]
What I have already done is 
1. Install dependency under push-est-public/
source install.sh

2. Install isam with /push-est-public/catkin_ws/src/isam_pose/install.sh

3. modify ~/push-est-public/software/config/environment.sh
brute force modify CODE_BASE and DATA_BASE, because regular  expression not work for me.
![push-env](https://user-images.githubusercontent.com/7314531/33742658-5afb062c-dbe4-11e7-960c-34fcd6aee8f5.png)

Now I can run pman 5-rviz, 9-isam-ros 1-playback rect1

but the behavior is wired,  the red rectangle not be tracked.
Video 
https://youtu.be/4ZsMMVBa8hI 
I haven't dive into the details yet.

the other question is pman  9-isam command. 
Is that for none ros code testing?
(before 9-isam-ros)
because cannot fond the executable 
```bash=
/home/rapyuta/push-est-public/catkin_ws/src/isam_pose/cmake-build-debug/devel/lib/isam_pose/isam_pose --shape-id rect1  --doEKF
```
I also change  my path,  how to generate cmake-build-debug/devel/lib/isam_pose/isam_pose executable.

Thank you in advance!

**Comment by peterkty** [comment]
You should use ```/home/mcube/push/catkin_ws/devel/lib/isam_pose --shape-id rect1  --doEKF```
or try ```rosrun isam_pose isam_pose```

Shape-id says which object are you using. The object in the video you showed is called ```butter```.
So do ```rosrun isam_pose isam_pose --shape-id butter```

In the video, that visualization is not right. I think the isam didn't run correctly. It's better to relaunch everything when you play another bag file. The timing of launching things is also important. Therefore, I often use the scripts in pman to do launch roscore, play bag file, and run the isam_pose program.

I used CLion to compile it, and Clion generate the executable here:
```/home/rapyuta/push-est-public/catkin_ws/src/isam_pose/cmake-build-debug/devel/lib/isam_pose/isam_pose```

**Comment by YuehChuan** [comment]
I'll try it soon. Thanks for instructions.

**Comment by YuehChuan** [comment]
![butter](https://user-images.githubusercontent.com/7314531/33759332-e5807608-dc3c-11e7-8b90-8338e8c98603.png)
cool, at least now the shape is right. Thanks.

**Comment by YuehChuan** [comment]
YOOOOO, 
https://youtu.be/eFQQteh3z9s
At this time, I gave myself a slap on the shoulder, got a victory beer?

3 miner discussions. One as you had mentioned, the timing is important. Got issue that I need to restart iSAM node from time to time, when the prediction is freezed.
ex: like the one in 46-58sec  
https://www.youtube.com/watch?v=eFQQteh3z9s&feature=youtu.be#t=0m46s

Second, cyan means apriltag has been detected by the camera.  I wonder what is the yellow-brown beam mean? Emphasize the detection?
 
Third, I felt the rosbag motion is not as smooth as  which was provided in the website. Maybe somehow relate to my hardware? ( I7 cpu, 8G ram, on Industrial PC )
 
In sum, great work! 
I feel so happy that I can reproduce it.
Would make what have been done into gist, then close the issue.
Thank you Peter!

**Comment by peterkty** [comment]
I think the iSAM is frozen because in the main code I hacked it to only run for a fixed length of timesteps. That is only for experiment purpose, we don't need it in reality. Maybe you can try to extend that or remove that limit. 

The yellow beam shows if there is a successful apriltag detection at that timestep or not.

Yes, I see your playback is not as smooth. See if you can try on better hardware.

I'm glad that you can reproduce it. Let me know if you have further questions.

**Comment by YuehChuan** [comment]
TQ!
<img width="167" alt="kitti-love" src="https://user-images.githubusercontent.com/7314531/33821571-3f28e7a4-de8f-11e7-99df-9e014c6eb042.png">

**Comment by YuehChuan** [comment]
Summary  notes to reproduce 
https://hackmd.io/s/r1LOsh9XG#

Thank you Peter! :smiley:

**Comment by peterkty** [comment]
Thanks YuenChuan. Great work on making the wonderful instructions.

I believe many people will benefit from that.

Peter

**Comment by Yanxing-Shi** [comment]
> Summary notes to reproduce
> https://hackmd.io/s/r1LOsh9XG#
> 
> Thank you Peter!

Hello，do you have the same question?：
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
Could not find a package configuration file provided by "apriltags" with
any of the following names:

apriltagsConfig.cmake
apriltags-config.cmake
Add the installation prefix of "apriltags" to CMAKE_PREFIX_PATH or set
"apriltags_DIR" to a directory containing one of the above files. If
"apriltags" provides a separate development package or SDK, be sure it has
been installed.
Call Stack (most recent call first):
isam_pose/CMakeLists.txt:9 (find_package)
Please help me out，I will thank you very much.

**Comment by YuehChuan** [comment]
@syx0629  Hello, did you install dependency yet ?
`source install.sh` 
try the step https://github.com/mcubelab/push-est-public/issues/1#issuecomment-350120390
there is the part to install apriltags
https://github.com/mcubelab/push-est-public/blob/master/install.sh#L110
