### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Yanxing-Shi** [mcubelab/push-est-public#2]
Hello, I made the following mistakes in the replication experiment：
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "apriltags" with
  any of the following names:

    apriltagsConfig.cmake
    apriltags-config.cmake

  Add the installation prefix of "apriltags" to CMAKE_PREFIX_PATH or set
  "apriltags_DIR" to a directory containing one of the above files.  If
  "apriltags" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  isam_pose/CMakeLists.txt:9 (find_package)
Please help me out，I will thank you very much.

**Comment by peterkty** [comment]
Sorry I’m a bit busy recently to help you with the problem. Have you looked at the thread in issue #1 to find some clue? I remember you probably don’t need that package if you use the ROS bag file.

**Comment by YuehChuan** [comment]
Hello, did you install dependency yet ?
`source install.sh` 
try the step https://github.com/mcubelab/push-est-public/issues/1#issuecomment-350120390
there is the part to install apriltags
https://github.com/mcubelab/push-est-public/blob/master/install.sh#L110

**Comment by ninafiona** [comment]
I tried building with python 2.7, ros-melodic and Ubuntu 18.04 - I just replaced `kinetic` with `melodic` in the code.

I followed the instructions here https://hackmd.io/@3OnqnT1fTvGgrRoxGGdA-g/r1LOsh9XG?type=view# and had the same error coming up as above. Then, I followed the steps stated in #1 , but still the same error. 
I replaces `apriltags` with `apriltagscpp` and fixed some other small bugs coming up, but then I got this error:
```
/push-est-public/software/build/include/cppad/example/cppad_eigen.hpp:149:10: error: ‘significant_decimals_default_impl’ is not a class template
   struct significant_decimals_default_impl< CppAD::AD<Base>, false>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```
