### ISSUE TITLE
Visualizing pose estimation results after running isam_pose?

### ISSUE THREAD

**Issue by suddhu** [mcubelab/push-est-public#3]
Are there python or MATLAB scripts to visualize the state estimation results from the `shapeRecon-xxxx.json` file similar to Fig. 8 in the [paper](https://arxiv.org/pdf/1709.09694.pdf)?

**Comment by peterkty** [comment]
Hi Suddhu,

Thanks for asking. Sorry, it may take some time to find it and I'm pretty occupied recently. I hope it's not too hard for you to write something simple to visualize it.

Peter

**Comment by suddhu** [comment]
Hey Peter!

Never mind, `software/isamShapePose/script/displayResultFingers.py` seems to have what I need! I'm still getting acquainted with the codebase, so I'll let you know if I have any other questions. Thanks!

Best, 
Suddhu
